### ISSUE TITLE
Implement file system language

### ISSUE THREAD

**Issue by thsutton** [lancelet/bored-robot#3]
Data types:
- [x] `Path`

Should support, at least, the following operations:

- [x] `read file`
- [x] `write file` (testing)
- [x] `mkdir` (testing)
- [x] `list directory`
- [x] `does directory exist`
- [ ] `find`

And interpreters:

- [x] `IO interpreter`
- [ ] `pure stateful interpreter`

In branch `filesystem`.

**Comment by lancelet** [comment]
Closing; most stuff done. Other bits will become separate issues.
